language: node_js
node_js:
  - "0.12.1"
script: "npm run coverage"
after_script: "npm run coveralls"
env:
    global:
        - secure: "dTk9t4RIBYY2QlHvZL+MDOEoc0dSSI+wCTA7xGAOkBTPhKd00untidHQ/WcslFf7azWcSD50rnfbm4aw5WW2uUwdnrbaVDl3yoLAkWRWktPMdkbe193geOWfEwUPnC0Jaw5EqE6/HeWnu4ec5S9Auu8NwCpm4WqHRcyUhacVdfc="
